version: 2
jobs:
  build:
    working_directory: ~/tw-test-indexer
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn
          command: yarn install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: |
            ./scripts/generate-test-snapshot.sh
            git diff --exit-code ./test/allure-demo.ndjson
